### ISSUE TITLE
Validation warnings only reveal one problem at a time

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#133]
Validation warnings list only the first problem encountered when a single record may have several problems.  This can lead to many iterations before a user gets it right. 
Do a full validation procedure and sanity check before returning a failure message.

**Comment by JoshBone** [comment]
I've tried to solve this, but unfortunately since the DRF (django rest framework) working as is, this can't be achieved without major code-refactoring. Since this is a non-blocking issue, I'd suggest to leave this for the bug-fixing period. (I can explain in a longer way, but the point is, that it seems that if custom Field validation errors are raised, then it stops the validation-flow at that point. So probably all the validation logic should be taken out from it's current place and put in a separate validator class, which collects all the possible errors.)

**Comment by ctueck** [comment]
No easy solution and not a major issue.
