### ISSUE TITLE
Clear trash data from ETER records

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#144]
ETER records have trash data in some required fields.  Trash data should be automatically cleared during transformation.

Clear "a" and "m" from NAT ID
Clear "m" from ACRONYM (almost 1000 of these!)
Clear "0" from LAT and LONG (there are no actual figures in this set...the entire list is "0"...did we accidently erase the real figures?)
Clear "m" from website; (FLAG THE 21 RECORDS WITHOUT WEBSITE INFORMATION...FLAG 1 RECORD MISSING "http://")

***Already cleaned ISCED fields, so no trash data.  FYI, it looks like we are missing QF-EHEA levels from app. 300 records!"

**Comment by ctueck** [comment]
I had cleared most of the trash data with updates from OrgReg.

Just did in addition:

- Set LAT and LONG to SQL `null` rather than 0. Indeed, I think we had no proper LAT/LONG values for any of the ETER records. Only the ones from OrgReg have correct data.
- Set website to empty string where it was "m" or "-".
- Sanitised website_link: some imported data was lacking the `http://` prefix and a few individual cases were just weird.

**Comment by Gyukat** [comment]
When I mentioned that there was no LAT/LONG data from ETER at the advisory board, they said that there should be.  Given a brief sampling of the ETER system, it seems to be the case.  I think that maybe there was something wrong with our transfer of this data.
