### ISSUE TITLE
/browse/institutions/ - crossborder filter doesn't work

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#216]
Setting cross-border to true always leads to an empty result set - there might be only one actual cross-border report in the system, but for sure the FINEEC audit at Uni Graz (institutiton id 2) should qualify, as Austria is flagged as cross-border focus country for FINEEC.

**Comment by JoshBone** [comment]
Okay... So this one is also tricky a bit. :) I'd address  @Gyukat with this as well.
So I checked FINEEC. It has Austria and Finland as FocusCountries. 
Austria is checked as crossborder... So I'm thinking, since the country is crossboarder goes through reports and the agency who submitted the reports, there won't be any difference in the list of country is crossborder yes/no for FINEEC because they have both scenarios... How should this work correctly? (Same is true for ARACIS / Moldova) - We don't have a connection between the report and to which country it is submitted...

**Comment by JoshBone** [comment]
Okay... So this one is also tricky a bit. :) I'd address  @Gyukat with this as well.
So I checked FINEEC. It has Austria and Finland as FocusCountries. 
Austria is checked as crossborder... So I'm thinking, since the country is crossboarder goes through reports and the agency who submitted the reports, there won't be any difference in the list of country is crossborder yes/no for FINEEC because they have both scenarios... How should this work correctly? (Same is true for ARACIS / Moldova) - We don't have a connection between the report and to which country it is submitted...

**Comment by ctueck** [comment]
Hm, maybe we didn't discuss the logic of the filter earlier.

The idea was to show institutions with reports from agencies for which they are considered cross-border - i.e. the connection is via the country in which the institution is based.

So, for instance, Graz is based in Austria and has a review by FINEEC -> as Austria is a cross-border country for FINEEC it should show up. The various Finnish institutions have reveiws by FINEEC -> but Finland is not marked cross-border for FINEEC so they shouldn't show.

Likewise, Belgium instittutions have reports by NVAO -> Belgium is not marked as cross-border for NVAO so they shouldn't appear. (But of course in case they'd have an additional report by, say, FINEEC.)

**Comment by Gyukat** [comment]
So, the relation is from the agency to the report and the report to the institution.  You can pull the location from the institution based on a given report number and then check with the agency based on the same report number.  This will get you the list of cross border.  You should also be able as needed to say:
- how many cross border in a given country OR how many cross border performed by a certain agency.

**Comment by ctueck** [comment]
This is not a priority issue any more, as we're taking all advanced search options off the site for the time being.

However, for later reference and since I saw there were also some changes addressing this filter in your commit related to #218, the logic should be visible from this query:

```sql
select deqar_institutions.id,deqar_institutions.name_primary
from deqar_institutions
left join deqar_reports_institutions on deqar_reports_institutions.institution_id = deqar_institutions.id
left join deqar_reports on deqar_reports.id = deqar_reports_institutions.report_id
left join deqar_institution_countries on deqar_institution_countries.institution_id = deqar_institutions.id
left join deqar_agency_focus_countries on (
    deqar_agency_focus_countries.agency_id = deqar_reports.agency_id
    and
    deqar_agency_focus_countries.country_id = deqar_institution_countries.country_id )
where deqar_agency_focus_countries.country_is_crossborder
group by deqar_institutions.id,deqar_institutions.name_primary;
```

In the test database this yields 57 rows -> institutions with at least one report by an agency for whom the institution's country is marked as "cross-border". In the live database, this yields exactly one row at the moment, Uni Graz, which is accurate.

**Comment by Gyukat** [comment]
@ctueck @JoshBone What is the status on this?

**Comment by ctueck** [comment]
Seems to work fine in v2 API, thus closing this.
