### ISSUE TITLE
/browse/institutions/ - report year filter extremely slow

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_backend#218]
Using the filter based on report year makes the search **extremely** slow.

It seems to happen only for those years for which there are any valid reports, e.g. queries for 2009 or earlier seem usually okay, while queries with 2010 or later might take very long depending on the combination of other search criteria.

**Comment by JoshBone** [comment]
Hmm...
I'm trying on the backend.deqar.eu and if I'm using the search filter for years, results seems pretty quick. Can you paste some examples which are the filter combinations causing the error? 
As I told previously I think we should refactor the institution search a bit, since it's not going from the institution records, but rather from reports, so the more filters we are applying, the longer the join queries will be... I'd like to test a search engine solution (Elastic or Solr), but for that I need time .

**Comment by ctueck** [comment]
These are some examples:

 - <https://backend.deqar.eu/webapi/v1/browse/institutions/?query=&agency=&esg_activity=&country=141&qf_ehea_level=&status=&report_year=2017&focus_country_is_crossborder=>
 - <https://backend.deqar.eu/webapi/v1/browse/institutions/?query=&agency=17&esg_activity=&country=&qf_ehea_level=&status=&report_year=2016&focus_country_is_crossborder=>
 - <https://backend.deqar.eu/webapi/v1/browse/institutions/?query=&agency=37&esg_activity=&country=&qf_ehea_level=&status=&report_year=2016&focus_country_is_crossborder=>
 - <https://backend.deqar.eu/webapi/v1/browse/institutions/?query=&agency=&esg_activity=&country=17&qf_ehea_level=&status=&report_year=2016&focus_country_is_crossborder=>

The pattern might be that queries for countries/agencies with many reports are slow. At the same time, searching only by year (e.g. <https://backend.deqar.eu/webapi/v1/browse/institutions/?query=&agency=&esg_activity=&country=&qf_ehea_level=&status=&report_year=2016&focus_country_is_crossborder=>) without any other filters is fast.

**Comment by JoshBone** [comment]
Yeah... That's what I was afraid of in the beginning, that institution search will be slow if more and more institutions will be added. I definitely search for some alternate solution, either with additional search_tables or Solr or even using some noSQL storage for search. I have to investigate the available solutions. The problem is, that at the moment I'm in a place, where my internet access is quiet limited, so I can't promise this to be done by tomorrow. Sorry for that. Please tell on the UI meeting, that we are aware and improving.

**Comment by JoshBone** [comment]
So... Finally I was able to trace down the issue which was a weird one related to how django assembles the SQL queries with multiple filters and reverse relations.
https://github.com/carltongibson/django-filter/issues/745

What happened is, that the SQL created the same joins (with different aliases) if the filter included a reverse relation (institution -> report) which slowed down the query a lot...

The change I've made includes to flag the institution records with reports (every time an institution is added, removed this one is calculated with a post_add, post_remove signal) and the basic recordset of the query is now the list of institutions with has_report flag. 
The filters are act as "sticky" filters so no double-joins are created. This way the SQL execution time for edge cases you defined went down from ~16.000ms to ~32ms. 

Please try it on the backend.

**Comment by ctueck** [comment]
Uh, the double joins sounds crazy, I can see that it would have led to a tables with millions of rows created and stored internally.

I tested some case on backend.test.deqar.eu and it seems perfectly efficient now. Results are also consistent.
