### ISSUE TITLE
Valid_to date listed as today when none is entered

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#225]
When there is no valid to date entered, instead of calculating the 6 years it should, the system shows the valid to date as today.  

https://www.eqar.eu/qa-results/institution/?id=1121

**Comment by JoshBone** [comment]
That's a frontend thing:
https://backend.deqar.eu/webapi/v1/browse/reports/institutional/by-institution/1121/

The date is null, so probably in the frontend there is some default used...

**Comment by Gyukat** [comment]
Josh, weren't we supposed to set a default as 6 years from the valid_from date when no valid_to date was entered?  I thought this was set in the backend...though without actually filling in the field.  Can you remember?

**Comment by JoshBone** [comment]
Dunno, 
Please decide with Colin how it should be. 
Currently I'm checking the 6 years validation if there is no valid_to in the db. 
I can also set it manually, however if someone changes the valid_from date, things become a bit trickier (that's why I prefer to do dynamic check). 

So:
Option A) - valid_to date is not filled in the database, nor in the API. Calculations are done in the frontend
Option B) - valid_to date is not filled in the database, but the API sends back +6 years in this case
Option C) - valid_to date will be entered in the database, but there should be a check upon report save and recalculate the valid_to upon data update.

**Comment by Gyukat** [comment]
Hmmm...let's see.
A) possible option 
B) I like this
c) seems like complicated solution...

Will run it by Colin.

**Comment by Gyukat** [comment]
Colin says A.  This means it goes to Slik--who should be instructed to show nothing when nothing is passed.

**Comment by Gyukat** [comment]
I think you can close it.  I have added to slik.
