### ISSUE TITLE
Search results list should group all unit/subunits

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#228]
All institutions with the same parent institution should be grouped together on the results list.  The easiest way to do this is to list parent and then child for the result entry.  We then need to alphabetise by parent unit if there is one.

**Comment by Gyukat** [comment]
Josh, I think this is only for Slik...the API end points appears to have all relevant information.  Can you confirm?

**Comment by Gyukat** [comment]
@ctueck Do you want this to be handled by Slik or should Josh serve up something pre-digested?

**Comment by Gyukat** [comment]
@JoshBone Colin says that you provide the search results ORDER so this should reflect the new logic-i.e. results should be ordered as [parent institution/child institution] when there is a hierarchical arrangements.

**Comment by JoshBone** [comment]
Mmm... That's a bit more complicated I think, because if you'd like to group on the frontend, then:
A) there can't be any pagination, since you can't iterate through the results
B) the name of the current institution and the name of parent is in different fields... So it should be somehow listed in a way, that first it comes the parent, then right after that the children alphabetically... 

I have to think more about this, because it's not as easy as you might think.

**Comment by JoshBone** [comment]
So logically just to summarise, before I start implementing.
Since we are ordering results from the db ordering can be done via one, or multiple fields. 
So in this case we need a name_sort field which will have the value of the parent institution name if exists, or the name_primary. So ordering can be done by name_sort and name_primary. 

(If I would just store the name of the parent and I'd order by that name_parent and name_primary then those institutions which don't have parent would be always in the first place since the name_parent field would be empty. That's why I'd store name_sort with the condition I was writing above.)

How does this sound?

**Comment by JoshBone** [comment]
Obviously name_sort will be always updated when an institution (or institution name entry) or it's parent will be changed...

**Comment by Gyukat** [comment]
I would make one adjustment...I think it should have the value of: 1) the parent institution name + name_primary OR 2) just name_primary.  I mention this because we still need to sub-order all those institutions with the same parent institution (so the name of the mother institution should appear first and all the faculties should be ordered alphabetically just afterwards).

Like:

University of Catalonia
University of Catalonia / Faculty of Agriculture
University of Catalonia / Faculty of Astrophysics
University of Catalonia / Faculty of Beekeeping...
etc.

**Comment by JoshBone** [comment]
It's deployed to the test, please take a looksy. 
To be able to debug easier, I've added 'name_sort' to the display as well.

**Comment by Gyukat** [comment]
See my note in Slack...you should probably walk me through the solution a bit.
