### ISSUE TITLE
Sort order of Agency names on Country page Agency list

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#252]
It is currently sorted alphabetically.  We would like it to be sorted by number of institutions--i.e. an agency that has evaluated more institutions should come higher on the list.  If two agencies have the same number, the secondary logic can be alphabetical!

**Comment by JoshBone** [comment]
It's kind of an "ugly" solution, because it now sorts the paginated resultset (which is currently contains all the records because of the limit='999' params). The more elegant way would be to eliminate pagination which is relatively easy to do, I just don't want to do it at this right moment not to mess up the website (since in that case results won't be put under 'results key', but simply would display as a json array).

**Comment by ctueck** [comment]
Eliminating pagination here would make sense, as we won't come anywhere near to large-ish numbers in the foreseeable decades. ;)

Maybe you can do that on the testing branch and then we coordinate rolling this out to live with the next bigger release?
