### ISSUE TITLE
Deletion of reports from backend

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_backend#257]
Josh, a weird and perhaps interim problem...we just deleted all the reports uploaded by PKA.  The reports disappeared from the system, but the insitutions (without any reports) still show up in search hits.  Does this mean that the "has report" flag that you created needs to be turned off when we delete from the backend?

**Comment by JoshBone** [comment]
I mentioned in the related issue, that this has_report flag should be retriggered upon certain events (report deletion, report date modification, institution change, etc...). Since I'll modify the this concept and put the institution records in Solr, I haven't yet implemented the event triggers. I plan to finish the Solr indexing sometimes end of this week, then these event triggers will be deployed as well. 

Meanwhile there is a management command which recalculates the has_report values. These can be run periodically. Apologise for not explaining it in more detail.
