### ISSUE TITLE
Create Data Model

### ISSUE THREAD

**Issue by JoshBone** [EQAR/eqar_backend#5]
To be able to start efficiently, do the search & browse APIs for december we should create a useable data model (which we can tweak in the future).

**Comment by Gyukat** [comment]
This task has been moved ahead of the full requirements definition and use cases in order to speed up the delivery of front-end APIs.  We will tweak the data model as determined by further requirements work.  We have begun work on a preliminary data dictionary which will serve as the basis of the data model: (https://docs.google.com/spreadsheets/d/1iwEafs8jE875Vu7bgHbQ0-j47XLuOi3dr6FFJdsjJt8/edit#gid=0)

**Comment by Gyukat** [comment]
I have finished a draft data model based on preliminary discussions with EQAR.  We should still work on the historical versioning and develop the country table based on further feedback from EQAR.

https://docs.google.com/document/d/1q9ot8pogGgdGrtWhm6gvfACcnNdFU46k_m6zuoT5Q3M/edit#

**Comment by JoshBone** [comment]
I think we can consider this as closed, we can modify it later if needed.
